# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99167c12ad017c70e0b543d54d888ccbc381185ec3a1e3977998f7347dc5887b6b97986de9661ef0e08262294bc83c145aa86c9fa411c4c61f5119fb2edb9d2f

test:
  secret_key_base: 2fb44a3b070961f24e744f3739542956a6df46ffbfa5746b21adb85e7055cefcd99d16e7fbd92484b13f4488c39a0c3f9d6f2c9f4bd06fd52c2ce24dc298a8f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
